name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build_image:
    if: github.repository == 'jnovick/argocd-image-updater'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: argocd-image-updater
      - name: Setup qemu
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        run: |
          docker login --username AWS --password "${DOCKER_PASSWORD}" 171312943278.dkr.ecr.us-west-2.amazonaws.com
          IMAGE_PUSH=yes make multiarch-image
        working-directory: argocd-image-updater
        env:
          DOCKER_PASSWORD: ${{ secrets.ECR_TOKEN }}
